# Generated by Django 5.1.1 on 2024-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMIRecord',
        ),
    ]
