# Generated by Django 5.1.1 on 2024-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
